import React from "react";
import { Sparkles, Brain, CheckCircle2, AlertCircle, Database, ArrowRight, X } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

export interface MetricExplanation {
  metricName: string;
  metricValue: string;
  badgeVariant?: "emerald" | "amber" | "rose" | "blue" | "purple";
  whyItExists: string;
  dataEvidence: string[];
  suggestedSolution: string;
  actionPrompt?: string;
}

interface AiReasoningModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  explanation: MetricExplanation | null;
  onActionClick?: (prompt?: string) => void;
}

export function AiReasoningModal({
  open,
  onOpenChange,
  explanation,
  onActionClick,
}: AiReasoningModalProps) {
  if (!explanation) return null;

  const badgeStyles = {
    emerald: "bg-emerald-500/10 text-emerald-600 border-emerald-500/20 dark:text-emerald-400",
    amber: "bg-amber-500/10 text-amber-600 border-amber-500/20 dark:text-amber-400",
    rose: "bg-rose-500/10 text-rose-600 border-rose-500/20 dark:text-rose-400",
    blue: "bg-blue-500/10 text-blue-600 border-blue-500/20 dark:text-blue-400",
    purple: "bg-purple-500/10 text-purple-600 border-purple-500/20 dark:text-purple-400",
  };

  const styleClass = badgeStyles[explanation.badgeVariant || "emerald"];

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-md rounded-2xl p-6 border border-border shadow-xl bg-background">
        <DialogHeader className="space-y-2 pb-2 border-b border-border/50">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="p-2 rounded-xl bg-emerald-500/10 text-emerald-600 dark:text-emerald-400">
                <Brain className="h-5 w-5" />
              </div>
              <DialogTitle className="font-display text-lg font-bold text-foreground">
                AI Mentor Reasoning
              </DialogTitle>
            </div>
            <Badge variant="outline" className={`font-mono text-xs px-2.5 py-0.5 ${styleClass}`}>
              {explanation.metricName}: {explanation.metricValue}
            </Badge>
          </div>
          <DialogDescription className="text-xs text-muted-foreground">
            Analysis generated by inspecting your learning behavior, quiz accuracy, and study logs.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 pt-3 text-xs leading-relaxed">
          {/* Section 1: Why this risk / score exists */}
          <div className="p-3 rounded-xl bg-secondary/50 border border-border/60 space-y-1.5">
            <div className="font-semibold text-foreground flex items-center gap-1.5 text-xs">
              <Sparkles className="h-3.5 w-3.5 text-amber-500" />
              <span>1. Why this status exists:</span>
            </div>
            <p className="text-muted-foreground">{explanation.whyItExists}</p>
          </div>

          {/* Section 2: Underlying Data Evidence */}
          <div className="space-y-1.5">
            <div className="font-semibold text-foreground flex items-center gap-1.5 text-xs">
              <Database className="h-3.5 w-3.5 text-sky-500" />
              <span>2. Empirical data evaluated:</span>
            </div>
            <div className="space-y-1 pl-1">
              {explanation.dataEvidence.map((item, idx) => (
                <div key={idx} className="flex items-start gap-2 text-muted-foreground">
                  <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500 shrink-0 mt-0.5" />
                  <span>{item}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Section 3: AI Suggested Solution */}
          <div className="p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-950 dark:text-emerald-200 space-y-1.5">
            <div className="font-semibold flex items-center gap-1.5 text-xs text-emerald-700 dark:text-emerald-300">
              <CheckCircle2 className="h-3.5 w-3.5 text-emerald-600" />
              <span>3. AI Recommended Solution:</span>
            </div>
            <p>{explanation.suggestedSolution}</p>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="pt-3 flex items-center justify-end gap-2 border-t border-border/50">
          <Button variant="outline" size="sm" onClick={() => onOpenChange(false)} className="text-xs">
            Close
          </Button>
          {explanation.actionPrompt && (
            <Button
              size="sm"
              className="bg-emerald-700 hover:bg-emerald-800 text-white font-semibold text-xs gap-1.5"
              onClick={() => {
                onOpenChange(false);
                onActionClick?.(explanation.actionPrompt);
              }}
            >
              <span>Execute Solution with AI</span>
              <ArrowRight className="h-3.5 w-3.5" />
            </Button>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
